name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this pipeline when code is pushed to the 'main' branch.
  pull_request:
    branches:
      - main  # Trigger this pipeline when a pull request is made to the 'main' branch.

jobs:
  # Job to run tests and linting
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linting
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

  # Job to build Docker image and push to Docker Hub
  docker_build:
    needs: test  # This ensures the test job runs before this job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t yourusername/mood-playlist-generator .

      - name: Push Docker image to Docker Hub
        run: |
          docker push yourusername/mood-playlist-generator

  # Job to deploy to Heroku (Optional, can use Render/Kubernetes)
  deploy:
    needs: docker_build  # This ensures the Docker build runs before deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Heroku
        uses: akshnz/heroku-cli-action@v1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/your-app-name.git
          git push heroku main
